spring.application.name=auth-gateway

# 1. Kill the startup noise
# spring.main.banner-mode=off
logging.level.org.springframework=WARN
logging.level.org.apache=WARN
logging.level.org.apache.tomcat=WARN
logging.level.org.apache.catalina=WARN

# 2. Keep YOUR app's logs visible
logging.level.com.fahim1837=DEBUG

# 3. Log every API hit (method + path)
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
